### ISSUE TITLE
Epic grid system

### ISSUE THREAD

**Issue by zhoraygevorgyan** [epicbg/epic-ui#30]
# Introduction to epic grid concept

## 1. The idea
We want to create a grid system for the front end framework, which will be flexible, easy to use, with lots of customizability. In most other frameworks there are a set of set breakpoints and container widths, which are tied together. We want to separate the two, meaning that whenever you add a new breakpoint, and add a container to it, the width of the container is calculated based on the breakpoint width. Therefore one can easily add more breakpoints and containers.

![image](https://user-images.githubusercontent.com/53972372/67636946-54c2ee00-f8de-11e9-9edf-183a506ae8dd.png)

## 2. Breakpoints
Starting with the breakpoints. **The user must be able to customize and add onto the existing breakpoints with css variables**. The 5 standard breakpoints are:

- 1920px Large desktop

- 1440px Desktop

- 1140px Laptop

- 720px Tablet

- 420px Mobile

*These may vary*

One should be able to customize and add new breakpoints from one place. Then using variables, they get implemented throughout the whole framework, enabling the user to have unlimited layout options.

## 3. Containers 
Most frameworks have a wrapper class of .container and it is the same for every page of the website. We want to make it, so that one can create multiple container classes with different widths, in order to have greater flexibility.
Also most frameworks have a standard container width, which is burdensome to change, if you are to customize the framework. We want to enable the user to customize the width of the container, and the best way in our opinion, is to have it's width calculated by the breakpoint's width.
![image](https://user-images.githubusercontent.com/53972372/67636577-d0bb3700-f8da-11e9-8a37-3d2ac78d0145.png)

**Create container helper classes which define container size .container (.is-xs, .is-sm, .is-md, is-lg).**
Each class will have different size on desktop, and all of them scale down to full-width container when they reach mobile breakpoint.
![image](https://user-images.githubusercontent.com/53972372/67636513-1d524280-f8da-11e9-83b6-ac31e7a1df86.png)

For example:
We create a new container class called .container-a
We want to set it's width for the different breakpoints
We do so by using a percentage of the breakpoint ( if we want to create a container, which is 1152px wide and is shown after the breakpoint of 1440, we calculate 80% of that breakpoint.)

Then the user specifies a percantage for every breakpoint he has created.

For example:
.container-a
\>1920px : 80% (Large desktop)
1440px-1920px : 80% (Desktop)
1140px-1440px : 90% (Laptop)

The user should also be able to declare if he wants to use a fluid container for certain breakpoints. This is mostly used in mobile and tablet, where the container takes the full width of the browser.

For example:
.container-a
420px-720px : fluid
<420px : fluid

Having set up containers from the beginning, one can now use different container widths in different pages, or on the same page, when one wants to achieve a more interesting layout.

## 4. Columns
Columns are an important part of building page layouts. We see one main thing that can be improved from most other frameworks. This is the abiliity to specify custom breakpoints to columns. In other frontend frameworks one uses col-md-4 to have a column that is 4 columns wide. But if one wants to have the column be 3 columns wide on a certain portion of that "md breakpoint", one must write custom css. Therefore one needs to add one more breakpoint, concerning the layout of the columns. We want this to be built into the framework. This happens mostly on tablet, where the container is fluid and the columns need to change their layout when the tablet is turned in landscape view. So we want to have sub breakpoints for the columns.

For example:
col-md-4 : makes a column, which is 4 columns wide for tablet (420px-720px).
col-md-a-6 : makes a column, which is 6 columns wide for a specific portion of tablet (lets say from 420px-540px).

These intermediary breakpoints for the columns should be customizable and one should be able to easily add new from one place.

![image](https://user-images.githubusercontent.com/53972372/67636622-46bf9e00-f8db-11e9-9304-fb911f7760d3.png)

# Getting started with the task
This large task is open to small and large contributions. This task is not meant for a single developer rather for long term development and contribution.
All grid files are stored in `src/scss/grid` folder. 
You can find grid variables in `src/scss/grid/_grid_variables.scss`
Container classes are stored in `src/scss/grid/containers.scss`
Grid system is stored in `src/scss/grid/grid.scss`
Grid system HELPERS are stored in `src/scss/grid/helpers.scss`

 
# Features done until now
- [ ] Create multiple container classes with different customizable widths
- [ ] Control container widths  based on breakpoints with calc function
- [ ] Create 5 customizable breakpoints through css variables
- [ ] Create column classes for every breakpoint (xl, lg, md, sm, xs)
- [ ] Create intermediary breakpoint classes for the colums (lga, lgb, lgc, lgd, lde, etc.)
